# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 363)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 541, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.phon_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.phon_label.setObjectName("phon_label")
        self.verticalLayout.addWidget(self.phon_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contactName = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.contactName.setObjectName("contactName")
        self.verticalLayout_2.addWidget(self.contactName)
        self.contactNumber = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.contactNumber.setObjectName("contactNumber")
        self.verticalLayout_2.addWidget(self.contactNumber)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.addContactBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addContactBtn.setObjectName("addContactBtn")
        self.horizontalLayout.addWidget(self.addContactBtn)
        self.contactList = QtWidgets.QListWidget(self.centralwidget)
        self.contactList.setGeometry(QtCore.QRect(50, 140, 401, 192))
        self.contactList.setObjectName("contactList")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_label.setText(_translate("MainWindow", "Name"))
        self.phon_label.setText(_translate("MainWindow", "Phone"))
        self.addContactBtn.setText(_translate("MainWindow", "PushButton"))
