from PyQt5 import QtCore, QtGui, QtWidgets  
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 200)
        MainWindow.setMinimumSize(QtCore.QSize(650, 200))
        MainWindow.setMaximumSize(QtCore.QSize(650, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 611, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.blue1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.blue1.setObjectName("blue1")
        self.color_group_1 = QtWidgets.QButtonGroup(MainWindow)
        self.color_group_1.setObjectName("color_group_1")
        self.color_group_1.addButton(self.blue1)
        self.verticalLayout.addWidget(self.blue1)
        self.red1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.red1.setObjectName("red1")
        self.color_group_1.addButton(self.red1)
        self.verticalLayout.addWidget(self.red1)
        self.green1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.green1.setObjectName("green1")
        self.color_group_1.addButton(self.green1)
        self.verticalLayout.addWidget(self.green1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.blue2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.blue2.setObjectName("blue2")
        self.color_group_2 = QtWidgets.QButtonGroup(MainWindow)
        self.color_group_2.setObjectName("color_group_2")
        self.color_group_2.addButton(self.blue2)
        self.verticalLayout_2.addWidget(self.blue2)
        self.red2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.red2.setObjectName("red2")
        self.color_group_2.addButton(self.red2)
        self.verticalLayout_2.addWidget(self.red2)
        self.green2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.green2.setObjectName("green2")
        self.color_group_2.addButton(self.green2)
        self.verticalLayout_2.addWidget(self.green2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.blue3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.blue3.setObjectName("blue3")
        self.color_group_3 = QtWidgets.QButtonGroup(MainWindow)
        self.color_group_3.setObjectName("color_group_3")
        self.color_group_3.addButton(self.blue3)
        self.verticalLayout_3.addWidget(self.blue3)
        self.red3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.red3.setObjectName("red3")
        self.color_group_3.addButton(self.red3)
        self.verticalLayout_3.addWidget(self.red3)
        self.green3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.green3.setObjectName("green3")
        self.color_group_3.addButton(self.green3)
        self.verticalLayout_3.addWidget(self.green3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 140, 611, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.result = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.result.setText("")
        self.result.setObjectName("result")
        self.horizontalLayout_2.addWidget(self.result)
        self.make_flag = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.make_flag.setObjectName("make_flag")
        self.horizontalLayout_2.addWidget(self.make_flag)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Color #1"))
        self.blue1.setText(_translate("MainWindow", "Синий"))
        self.red1.setText(_translate("MainWindow", "Красный"))
        self.green1.setText(_translate("MainWindow", "Зелёный"))
        self.label_2.setText(_translate("MainWindow", "Color #2"))
        self.blue2.setText(_translate("MainWindow", "Синий"))
        self.red2.setText(_translate("MainWindow", "Красный"))
        self.green2.setText(_translate("MainWindow", "Зелёный"))
        self.label_3.setText(_translate("MainWindow", "Color #3"))
        self.blue3.setText(_translate("MainWindow", "Синий"))
        self.red3.setText(_translate("MainWindow", "Красный"))
        self.green3.setText(_translate("MainWindow", "Зелёный"))
        self.make_flag.setText(_translate("MainWindow", "PushButton"))


class FlagMaker(QMainWindow, Ui_MainWindow):
    buttons = dict()
    request, now = "0", ""

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.make_flag.clicked.connect(self.makes_flag)

    def makes_flag(self):
        f = [i.text() for i in self.color_group_1.buttons() if i.isChecked()]
        s = [i.text() for i in self.color_group_2.buttons() if i.isChecked()]
        t = [i.text() for i in self.color_group_3.buttons() if i.isChecked()]

        self.result.setText(f"Цвета: {f[0]}, {s[0]} и {t[0]}")


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ex = FlagMaker()
    ex.show()
    sys.exit(app.exec_())
