# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 96)
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(10, 40, 65, 20))
        self.button.setObjectName("button")
        self.text_field = QtWidgets.QTextEdit(Form)
        self.text_field.setGeometry(QtCore.QRect(100, 20, 271, 64))
        self.text_field.setObjectName("text_field")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button.setText(_translate("Form", "PushButton"))
