# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './acronym.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.stones = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.stones.setObjectName("stones")
        self.horizontalLayout.addWidget(self.stones)
        self.setButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.setButton.setObjectName("setButton")
        self.horizontalLayout.addWidget(self.setButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.remainLcd = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.remainLcd.setObjectName("remainLcd")
        self.verticalLayout.addWidget(self.remainLcd)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.takeinput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.takeinput.setObjectName("takeinput")
        self.horizontalLayout_2.addWidget(self.takeinput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.takeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.takeButton.setObjectName("takeButton")
        self.verticalLayout.addWidget(self.takeButton)
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.resultLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.resultLabel.setFont(font)
        self.resultLabel.setTextFormat(QtCore.Qt.AutoText)
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout.addWidget(self.resultLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Stones:"))
        self.setButton.setText(_translate("Form", "Set"))
        self.label_2.setText(_translate("Form", "Take amount"))
        self.takeButton.setText(_translate("Form", "Take"))
        self.resultLabel.setText(_translate("Form", "TextLabel"))
